events {
  worker_connections 1024;
}

http {
  resolver 127.0.0.11 valid=10s;

  map $uri $upstream_target {
    /v1/user    http://security:3000/v1/user;
    /v1/upload  http://uploader:3000/v1/upload;
  }

  server {
    listen 8080;

    location = /v1/register {
      proxy_pass http://security:3000/v1/user;
    }

    location = /v1/token {
      proxy_pass http://security:3000/v1/token;
    }

    location ~ ^/v1/(user|upload)$ {
      auth_request /_validate_token;
      proxy_pass $upstream_target;
      proxy_set_header Authorization $http_authorization;
    }

    location ~ ^/v1/user/(?<image>.+)$ {
      auth_request /_validate_token;

      proxy_pass http://storage:9000/images/$image;
      proxy_set_header Authorization $http_authorization;
    }

    location = /_validate_token {
      internal;

      proxy_pass http://security:3000/v1/token/validation;
      proxy_pass_request_body off;
      proxy_set_header Content-Length "";
      proxy_set_header Authorization $http_authorization;
    }
  }
}